import Link from "next/link";
import { ArrowRight, Users, Target, Compass, Eye } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

import { getCurrentUser } from "@/lib/supabase/with-role";

export default async function LandingPage() {
  const user = await getCurrentUser();
  const isScout = user?.role === "scout" || user?.role === "admin";

  return (
    <div className="flex flex-col">
      {/* Hero */}
      <section className="relative overflow-hidden border-b">
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(circle_at_top,theme(colors.primary.DEFAULT/15%),transparent_60%)]"
        />
        <div className="container mx-auto px-4 py-20 md:py-28">
          <div className="mx-auto max-w-3xl text-center">
            <Badge variant="secondary" className="mb-6">
              Human-scouted · Africa-focused
            </Badge>
            <h1 className="text-4xl font-bold tracking-tight md:text-6xl">
              Every great African player
              <br className="hidden md:block" />
              starts with a scout on the ground.
            </h1>
            <p className="mt-6 text-lg text-muted-foreground md:text-xl">
              ScoutingReport Africa is a platform for structured, human-written
              scout reports on players the major data providers miss — from
              CAF continental competitions down to youth academies.
            </p>
            <div className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row">
              <Link href="/players" className={buttonVariants({ size: "lg" })}>
                Browse players
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
              {isScout ? (
                <Link
                  href="/scout/dashboard"
                  className={buttonVariants({ variant: "default", size: "lg", className: "bg-orange-600 hover:bg-orange-700" })}
                >
                  Go to Dashboard
                </Link>
              ) : (
                <Link
                  href="/auth/sign-in?next=/scout/dashboard"
                  className={buttonVariants({ variant: "outline", size: "lg" })}
                >
                  Scouts sign in
                </Link>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* Value prop cards */}
      <section className="border-b bg-muted/30">
        <div className="container mx-auto px-4 py-16">
          <div className="mx-auto grid max-w-5xl gap-4 md:grid-cols-3">
            {[
              {
                icon: Users,
                title: "Written by scouts",
                body: "Every report follows a structured 10-section template covering technical, tactical, physical, and mentality assessment — no autogenerated stats pretending to be judgment.",
              },
              {
                icon: Compass,
                title: "Africa-first coverage",
                body: "From the CAF Champions League and AFCON down to domestic leagues, women's football, and youth academies the major platforms ignore.",
              },
              {
                icon: Target,
                title: "Built for recruiters",
                body: "Filter by position, age, nationality, and rating. Save watchlists. Compare players side-by-side on radar charts. No fluff, no paywall for v1.",
              },
            ].map((item) => (
              <Card
                key={item.title}
                className="p-6 flex flex-col gap-3 border-border"
              >
                <item.icon className="h-5 w-5 text-primary" />
                <h3 className="font-semibold">{item.title}</h3>
                <p className="text-sm text-muted-foreground">{item.body}</p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="border-b">
        <div className="container mx-auto px-4 py-20">
          <div className="mx-auto max-w-3xl text-center">
            <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
              How it works
            </h2>
            <p className="mt-4 text-muted-foreground">
              The same 10-section structure every time, so reports are
              comparable across scouts, players, and matches.
            </p>
          </div>
          <div className="mx-auto mt-12 grid max-w-5xl gap-4 md:grid-cols-4">
            {[
              ["1", "Player information", "Name, DOB, club, position, foot."],
              ["2", "Match context", "Live vs video, minutes observed, role played."],
              ["3", "Four pillars", "Technical, tactical, physical, mentality — each rated 1–5 with notes."],
              ["4", "Recommendation", "Sign now, monitor, pass, or revisit — with projection and fit."],
            ].map(([n, title, body]) => (
              <div key={n} className="rounded-lg border p-5">
                <div className="mb-3 inline-flex h-7 w-7 items-center justify-center rounded-full bg-primary/10 text-xs font-semibold text-primary">
                  {n}
                </div>
                <p className="font-medium">{title}</p>
                <p className="mt-1 text-sm text-muted-foreground">{body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section>
        <div className="container mx-auto px-4 py-20">
          <div className="mx-auto max-w-3xl rounded-2xl border bg-card p-10 text-center">
            <Eye className="mx-auto h-8 w-8 text-primary" />
            <h2 className="mt-4 text-2xl font-bold tracking-tight md:text-3xl">
              Become a scout on the platform
            </h2>
            <p className="mt-3 text-muted-foreground">
              We're inviting a founding group of scouts based in and around CAF
              nations to contribute reports. If that's you, get in touch.
            </p>
            <Link
              href="/about"
              className={buttonVariants({ className: "mt-6" })}
            >
              Apply to contribute
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
